import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const source = path => readFile(new URL('../' + path, import.meta.url), 'utf8')
test('approved river loop remains a local fast-start H264 asset', async () => {
  const video = await readFile(new URL('../public/forest/forest-loop.mp4', import.meta.url))
  assert.equal(video.toString('ascii', 4, 8), 'ftyp')
  assert.ok(video.includes(Buffer.from('avc1')))
  const moov = video.indexOf(Buffer.from('moov'))
  assert.ok(moov >= 0 && moov < video.indexOf(Buffer.from('mdat')))
  assert.ok(video.length < 1000000)
})
test('homepage uses a video-frame image while the clip loads', async () => {
  const poster = await readFile(new URL('../public/forest/forest-loop-poster.webp', import.meta.url))
  assert.equal(poster.toString('ascii', 8, 12), 'WEBP')
  assert.ok(poster.length < 300000)
  const css = await source('components/home/forest.module.css')
  const player = await source('components/home/ForestExperience.tsx')
  assert.match(css, /forest-loop-poster\.webp/)
  assert.match(player, /poster="\/forest\/forest-loop-poster\.webp"/)
})
test('homepage uses approved video without the rejected depth scene', async () => {
  const home = await source('components/home/ForestExperience.tsx')
  assert.match(home, /<video/)
  assert.match(home, /forest-loop.mp4/)
  assert.doesNotMatch(home, /<ForestScene/)
  assert.match(home, /data-testid="forest-hero"/)
  assert.match(home, /prefers-reduced-motion/)
})
test('the animated scene ends with the hero and lower sections use regular layout', async () => {
  const home = await source('components/home/ForestExperience.tsx')
  const css = await source('components/home/forest.module.css')
  const page = await source('app/page.tsx')
  assert.match(css, /heroBackdrop\s*\{\s*position:\s*absolute/)
  assert.match(css, /guideInner,\.speciesInner\s*\{[^}]*display:\s*grid/)
  assert.match(page, /className=\{styles\.guideInner\}/)
  assert.match(page, /className=\{styles\.speciesInner\}/)
  assert.doesNotMatch(home, /preventDefault/)
  assert.doesNotMatch(css, /forest-bank-transition\.webp/)
})
test('home typography supports Thai UI and a distinctive hero heading', async () => {
  const layout = await source('app/layout.tsx')
  const page = await source('app/page.tsx')
  const css = await source('components/home/forest.module.css')
  assert.match(layout, /Noto_Sans_Thai/)
  assert.match(page, /Newsreader/)
  assert.match(css, /var\(--font-ui\)/)
  assert.match(css, /var\(--font-display\)/)
})
test('the homepage explains image suggestions without claiming certainty', async () => {
  const page = await source('app/page.tsx')
  assert.match(page, /possible species match/)
  assert.match(page, /not a medical diagnosis/)
  assert.match(page, /not safety decisions/)
})
test('homepage connects to real analysis and export flows without a motion control', async () => {
  const page = await source('app/page.tsx')
  const player = await source('components/home/ForestExperience.tsx')
  const css = await source('components/home/forest.module.css')
  assert.match(page, /Detected region/)
  assert.match(page, /Confidence &amp; reference/)
  assert.match(page, /href="\/export"/)
  assert.doesNotMatch(player, /motionControl|Pause motion|Resume motion/)
  assert.doesNotMatch(css, /\.motionControl/)
})
test('homepage restores the original forest closing and footer', async () => {
  const page = await source('app/page.tsx')
  const css = await source('components/home/forest.module.css')
  assert.match(page, /See nature differently\./)
  assert.match(page, /Back to the forest/)
  assert.match(css, /\.closing \{[^}]*text-align:center;[^}]*background:#142b2d/)
  assert.match(css, /\.footer \{[^}]*background:#142b2d/)
})
test('homepage retains working destinations and original navigation theme', async () => {
  const page = await source('app/page.tsx')
  assert.match(page, /href="\/predict"/)
  assert.match(page, /id="guide"/)
  assert.match(page, /id="species"/)
  const nav = await source('components/layout/Navbar.tsx')
  assert.match(nav, /bg-zinc-950\/80/)
  assert.match(nav, /text-emerald-500/)
})
