import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const source = path => readFile(new URL('../' + path, import.meta.url), 'utf8')
test('approved river loop remains a local fast-start H264 asset', async () => {
  const video = await readFile(new URL('../public/forest/forest-loop.mp4', import.meta.url))
  assert.equal(video.toString('ascii', 4, 8), 'ftyp')
  assert.ok(video.includes(Buffer.from('avc1')))
  const moov = video.indexOf(Buffer.from('moov'))
  assert.ok(moov >= 0 && moov < video.indexOf(Buffer.from('mdat')))
  assert.ok(video.length < 1000000)
})
test('homepage uses a video-frame image while the clip loads', async () => {
  const poster = await readFile(new URL('../public/forest/forest-loop-poster.webp', import.meta.url))
  assert.equal(poster.toString('ascii', 8, 12), 'WEBP')
  assert.ok(poster.length < 300000)
  const css = await source('components/home/forest.module.css')
  const player = await source('components/home/ForestExperience.tsx')
  assert.match(css, /forest-loop-poster\.webp/)
  assert.match(player, /poster="\/forest\/forest-loop-poster\.webp"/)
})
test('homepage uses approved video without the rejected depth scene', async () => {
  const home = await source('components/home/ForestExperience.tsx')
  assert.match(home, /<video/)
  assert.match(home, /forest-loop.mp4/)
  assert.doesNotMatch(home, /<ForestScene/)
  assert.match(home, /data-testid="forest-hero"/)
  assert.match(home, /prefers-reduced-motion/)
})
test('the animated scene ends with the hero and lower sections use regular layout', async () => {
  const home = await source('components/home/ForestExperience.tsx')
  const css = await source('components/home/forest.module.css')
  const page = await source('app/page.tsx')
  assert.match(css, /heroBackdrop\s*\{\s*position:\s*absolute/)
  assert.match(css, /\.guideInner\s*\{[^}]*display:\s*grid/)
  assert.match(css, /\.speciesList\s*\{[^}]*border-top:/)
  assert.match(css, /\.speciesItem summary\s*\{[^}]*display:\s*grid/)
  assert.match(page, /className=\{styles\.guideInner\}/)
  assert.match(page, /className=\{styles\.speciesInner\}/)
  assert.doesNotMatch(home, /preventDefault/)
  assert.doesNotMatch(css, /forest-bank-transition\.webp/)
})
test('home typography uses a strong shared UI font without the former italic display face', async () => {
  const layout = await source('app/layout.tsx')
  const page = await source('app/page.tsx')
  const css = await source('components/home/forest.module.css')
  assert.match(layout, /Noto_Sans_Thai/)
  assert.doesNotMatch(page, /Newsreader|<em>/)
  assert.match(page, /Analyze a snake photo\./)
  assert.match(page, /Understand the result\./)
  assert.match(css, /var\(--font-ui\)/)
  assert.doesNotMatch(css, /var\(--font-display\)/)
  assert.match(css, /\.hero h1 \{[^}]*font-weight:700/)
  assert.match(css, /\.heroNote \{[^}]*background:/)
  assert.doesNotMatch(page, /styles\.heroEyebrow|AI-assisted snake analysis<\/span>/)
  assert.doesNotMatch(css, /\.heroEyebrow/)
})
test('the homepage explains image suggestions without claiming certainty', async () => {
  const page = await source('app/page.tsx')
  const footer = await source('components/layout/Footer.tsx')
  assert.match(page, /possible species match/)
  assert.match(page, /not safety decisions/)
  assert.match(footer, /not medical advice or a safety guarantee/)
})
test('homepage connects to real analysis and export flows without a motion control', async () => {
  const page = await source('app/page.tsx')
  const player = await source('components/home/ForestExperience.tsx')
  const css = await source('components/home/forest.module.css')
  assert.match(page, /Detected region/)
  assert.match(page, /Confidence &amp; reference/)
  assert.match(page, /href="\/export"/)
  assert.doesNotMatch(player, /motionControl|Pause motion|Resume motion/)
  assert.doesNotMatch(css, /\.motionControl/)
})
test('species section shows every local sample rather than three handpicked entries', async () => {
  const page = await source('app/page.tsx')
  assert.match(page, /SNAKE_DATA\.map/)
  assert.match(page, /SNAKE_DATA\.length/)
  assert.doesNotMatch(page, /SNAKE_DATA\[0\], SNAKE_DATA\[2\], SNAKE_DATA\[4\]/)
  assert.match(page, /NOT THE FULL MODEL COVERAGE LIST/)
})
test('lower homepage sections keep dark surfaces with emerald accents', async () => {
  const css = await source('components/home/forest.module.css')
  assert.match(css, /\.resultPanel \{[^}]*background:#18181b/)
  assert.match(css, /\.steps \{[^}]*border-top:2px solid #059669[^}]*background:linear-gradient\(115deg,#202023,#18181b\)/)
  assert.match(css, /\.speciesItem \{[^}]*border-bottom:1px solid #3f3f46/)
  assert.match(css, /\.speciesItem:hover,\.speciesItem\[open\] \{[^}]*background:#ffffff09/)
  assert.match(css, /\.dataLink \{[^}]*border-left:2px solid #10b981/)
})
test('homepage uses the shared dark footer with scoped source attribution', async () => {
  const page = await source('app/page.tsx')
  const chrome = await source('components/layout/AppChrome.tsx')
  const footer = await source('components/layout/Footer.tsx')
  assert.doesNotMatch(page, /styles\.footer|styles\.closing/)
  assert.match(chrome, /!isAccessPage && <Footer \/>/)
  assert.match(footer, /bg-zinc-950/)
  assert.match(footer, /TH-BIF \/ ONEP/)
  assert.match(footer, /The Reptile Database/)
  assert.match(footer, /Queen Saovabha Memorial Institute/)
})
test('homepage retains working destinations and original navigation theme', async () => {
  const page = await source('app/page.tsx')
  assert.match(page, /href="\/predict"/)
  assert.match(page, /id="guide"/)
  assert.match(page, /id="species"/)
  const nav = await source('components/layout/Navbar.tsx')
  assert.match(nav, /bg-zinc-950\/80/)
  assert.match(nav, /text-emerald-500/)
})
