// Labels and ordering from Thai-Snake-Dataset v4 (nc: 25).
// Display names, Thai names, and families come from snake_species in Supabase.
// These training labels are not a claim about every deployed model release.
export const MODEL_CLASS_LABELS = [
  'Ahaetulla nasuta',
  'Ahaetulla prasina',
  'Boiga cyanea',
  'Boiga melanota',
  'Boiga multomaculata',
  'Boiga siamensis',
  'Bungarus fasciatus',
  'Bungarus wanghaotingi',
  'Calliophis maculiceps maculiceps',
  'Coelognathus radiatus',
  'Cylindrophis jodiae',
  'Daboia siamensis',
  'Dendrelaphis pictus',
  'Enhydris enhydris',
  'Enhydris plumbea',
  'Homalopsis buccata',
  'Lycodon davisonii',
  'Lycodon laoensis',
  'Malayopython reticulatus',
  'Naja kaouthia',
  'Oligodon taeniatus',
  'Psammodynastes pulverulentus',
  'Ptyas mucosa',
  'Trimeresurus albolabris',
  'Trimeresurus macrops',
] as const
