'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, Mail, Plus, ShieldCheck } from 'lucide-react'
import Button from '@/components/ui/Button'
import { supabase } from '@/lib/supabase/client'
import { useToast } from '@/components/ui/Toast'

type Expert = { id: string; full_name: string; specialty: string | null; status: 'active' | 'inactive' | 'pending'; verificationCount: number }

export default function AuthorizedExperts() {
  const { showToast } = useToast(); const [experts, setExperts] = useState<Expert[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState({ fullName: '', email: '', specialty: '' }); const [sending, setSending] = useState(false); const [removeTarget, setRemoveTarget] = useState<Expert | null>(null); const [removing, setRemoving] = useState(false)
  async function request(method: 'GET' | 'POST' | 'PATCH' | 'DELETE', body?: object) {
    const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('Sign in is required.')
    const response = await fetch('/api/admin/experts', { method, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? 'Request failed.'); return payload
  }
  async function load() { try { const payload = await request('GET'); setExperts(payload.experts) } catch (error) { showToast(error instanceof Error ? error.message : 'Could not load expert accounts.', 'error') }; setLoading(false) }
  useEffect(() => { load() }, [])
  async function invite(event: React.FormEvent) { event.preventDefault(); setSending(true); try { await request('POST', form); showToast('Invitation sent. Access will activate after password setup.'); setForm({ fullName: '', email: '', specialty: '' }); setOpen(false); await load() } catch (error) { showToast(error instanceof Error ? error.message : 'Could not invite expert.', 'error') }; setSending(false) }
  async function resendInvitation(expert: Expert) { setSending(true); try { await request('POST', { expertId: expert.id }); showToast('A new password link was sent.'); } catch (error) { showToast(error instanceof Error ? error.message : 'Could not resend the invitation.', 'error') }; setSending(false) }
  async function setStatus(expert: Expert, status: Expert['status']) { try { await request('PATCH', { id: expert.id, status }); showToast(`Account marked ${status}.`); await load() } catch (error) { showToast(error instanceof Error ? error.message : 'Could not update account.', 'error') } }
  async function removeExpert() { if (!removeTarget) return; setRemoving(true); try { await request('DELETE', { id: removeTarget.id }); showToast('Expert account removed.'); setRemoveTarget(null); await load() } catch (error) { showToast(error instanceof Error ? error.message : 'Could not remove expert account.', 'error') }; setRemoving(false) }

  return <section className="mt-12"><div className="mb-6 flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-medium text-zinc-100"><ShieldCheck size={20} className="text-zinc-500" /> Expert accounts</h2>{!open && <Button variant="ghost" onClick={() => setOpen(true)}><Plus size={16} /> Invite expert</Button>}</div>
    {open && <form onSubmit={invite} className="mb-5 grid gap-3 rounded-xl border border-zinc-800 bg-zinc-900/30 p-5 sm:grid-cols-3"><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Full name" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><input value={form.specialty} onChange={e => setForm({ ...form, specialty: e.target.value })} placeholder="Specialty (optional)" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><div className="sm:col-span-3 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={sending}>{sending ? 'Sending…' : 'Send invitation'}</Button></div></form>}
    <div className="overflow-x-auto rounded-xl border border-zinc-800 bg-zinc-900/20"><table className="w-full text-left"><thead><tr className="border-b border-zinc-800 bg-zinc-900/50 text-xs uppercase tracking-wider text-zinc-500"><th className="p-4">Expert</th><th className="p-4">Specialty</th><th className="p-4">Verifications</th><th className="p-4">Access</th><th className="p-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-800/50">{loading ? <tr><td colSpan={5} className="p-8 text-center text-zinc-500">Loading accounts…</td></tr> : experts.length === 0 ? <tr><td colSpan={5} className="p-8 text-center text-zinc-500">No expert accounts yet.</td></tr> : experts.map(expert => <tr key={expert.id} className="hover:bg-zinc-800/30"><td className="p-4 font-medium text-zinc-200">{expert.full_name}</td><td className="p-4 text-sm text-zinc-400">{expert.specialty || '—'}</td><td className="p-4 font-mono text-sm text-zinc-300">{expert.verificationCount}</td><td className="p-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${expert.status === 'active' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400' : expert.status === 'pending' ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-zinc-700 bg-zinc-800 text-zinc-400'}`}>{expert.status === 'active' ? 'Active' : expert.status === 'pending' ? 'Pending setup' : 'Inactive'}</span></td><td className="p-4"><div className="flex justify-end gap-1">{expert.status === 'pending' ? <Button size="sm" variant="ghost" disabled={sending} onClick={() => resendInvitation(expert)}><Mail size={14} /> Resend link</Button> : expert.status === 'active' ? <Button size="sm" variant="ghost" onClick={() => setStatus(expert, 'inactive')}>Suspend</Button> : <Button size="sm" onClick={() => setStatus(expert, 'active')}>Re-activate</Button>}{expert.verificationCount === 0 && <Button size="sm" variant="danger" onClick={() => setRemoveTarget(expert)}>Remove</Button>}</div></td></tr>)}</tbody></table></div>
    {removeTarget && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="remove-expert-title"><section className="w-full max-w-md rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl"><div className="flex items-start gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-red-500/10 text-red-400"><AlertTriangle size={20} /></div><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-red-400">Permanent action</p><h3 id="remove-expert-title" className="mt-1 text-lg font-medium text-zinc-100">Remove expert account?</h3></div></div><p className="mt-5 text-sm leading-6 text-zinc-400"><span className="font-medium text-zinc-200">{removeTarget.full_name}</span> will lose the invitation and account. This action cannot be undone.</p><div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-2.5 text-xs text-zinc-500">No verifications have been recorded, so no research review data will be removed.</div><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" disabled={removing} onClick={() => setRemoveTarget(null)}>Keep account</Button><Button variant="danger" disabled={removing} onClick={removeExpert}>{removing ? 'Removing…' : 'Remove account'}</Button></div></section></div>}
  </section>
}
