'use client'

import { useEffect, useState } from 'react'
import { Mail, Plus, ShieldCheck } from 'lucide-react'
import Button from '@/components/ui/Button'
import { supabase } from '@/lib/supabase/client'
import { useToast } from '@/components/ui/Toast'

type Expert = { id: string; full_name: string; specialty: string | null; status: 'active' | 'inactive' | 'pending'; verificationCount: number }

export default function AuthorizedExperts() {
  const { showToast } = useToast(); const [experts, setExperts] = useState<Expert[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState({ fullName: '', email: '', specialty: '' }); const [sending, setSending] = useState(false)
  async function request(method: 'GET' | 'POST' | 'PATCH', body?: object) {
    const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('Sign in is required.')
    const response = await fetch('/api/admin/experts', { method, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? 'Request failed.'); return payload
  }
  async function load() { try { const payload = await request('GET'); setExperts(payload.experts) } catch (error) { showToast(error instanceof Error ? error.message : 'Could not load expert accounts.', 'error') }; setLoading(false) }
  useEffect(() => { load() }, [])
  async function invite(event: React.FormEvent) { event.preventDefault(); setSending(true); try { await request('POST', form); showToast('Invitation sent. Approve the account after it is created.'); setForm({ fullName: '', email: '', specialty: '' }); setOpen(false); await load() } catch (error) { showToast(error instanceof Error ? error.message : 'Could not invite expert.', 'error') }; setSending(false) }
  async function resendInvitation(expert: Expert) { setSending(true); try { await request('POST', { expertId: expert.id }); showToast('A new password link was sent.'); } catch (error) { showToast(error instanceof Error ? error.message : 'Could not resend the invitation.', 'error') }; setSending(false) }
  async function setStatus(expert: Expert, status: Expert['status']) { try { await request('PATCH', { id: expert.id, status }); showToast(`Account marked ${status}.`); await load() } catch (error) { showToast(error instanceof Error ? error.message : 'Could not update account.', 'error') } }

  return <section className="mt-12"><div className="mb-6 flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-medium text-zinc-100"><ShieldCheck size={20} className="text-zinc-500" /> Expert accounts</h2><Button variant="ghost" onClick={() => setOpen(true)}><Plus size={16} /> Invite expert</Button></div>
    {open && <form onSubmit={invite} className="mb-5 grid gap-3 rounded-xl border border-zinc-800 bg-zinc-900/30 p-5 sm:grid-cols-3"><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Full name" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><input value={form.specialty} onChange={e => setForm({ ...form, specialty: e.target.value })} placeholder="Specialty (optional)" className="rounded-lg border border-zinc-800 bg-zinc-950 p-2 text-sm text-zinc-200" /><div className="sm:col-span-3 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={sending}>{sending ? 'Sending…' : 'Send invitation'}</Button></div></form>}
    <div className="overflow-x-auto rounded-xl border border-zinc-800 bg-zinc-900/20"><table className="w-full text-left"><thead><tr className="border-b border-zinc-800 bg-zinc-900/50 text-xs uppercase tracking-wider text-zinc-500"><th className="p-4">Expert</th><th className="p-4">Specialty</th><th className="p-4">Verifications</th><th className="p-4">Access</th><th className="p-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-800/50">{loading ? <tr><td colSpan={5} className="p-8 text-center text-zinc-500">Loading accounts…</td></tr> : experts.length === 0 ? <tr><td colSpan={5} className="p-8 text-center text-zinc-500">No expert accounts yet.</td></tr> : experts.map(expert => <tr key={expert.id} className="hover:bg-zinc-800/30"><td className="p-4 font-medium text-zinc-200">{expert.full_name}</td><td className="p-4 text-sm text-zinc-400">{expert.specialty || '—'}</td><td className="p-4 font-mono text-sm text-zinc-300">{expert.verificationCount}</td><td className="p-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${expert.status === 'active' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400' : expert.status === 'pending' ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-zinc-700 bg-zinc-800 text-zinc-400'}`}>{expert.status === 'active' ? 'Active' : expert.status === 'pending' ? 'Pending setup' : 'Inactive'}</span></td><td className="p-4 text-right">{expert.status === 'pending' ? <Button size="sm" variant="ghost" disabled={sending} onClick={() => resendInvitation(expert)}><Mail size={14} /> Resend link</Button> : expert.status === 'active' ? <Button size="sm" variant="ghost" onClick={() => setStatus(expert, 'inactive')}>Suspend</Button> : <Button size="sm" onClick={() => setStatus(expert, 'active')}>Approve</Button>}</td></tr>)}</tbody></table></div>
  </section>
}
